@MyGeminiAPI_HostAddress = http://localhost:5122


POST {{MyGeminiAPI_HostAddress}}/api/Gemini/generate-quiz
Content-Type : application/json
Accept: application/json

{
  "questionCount": 3,
  "categoryName": "Random",
  "questionType": "Mukltiple Options",
  "questionLevel": "Easy"
}

###