@MyGeminiAPI_HostAddress = http://localhost:5122

### Generating Quiz
POST {{MyGeminiAPI_HostAddress}}/api/Gemini/generate-quiz
Content-Type : application/json
Accept: application/json

{
  "questionCount": 3,
  "categoryName": "Random",
  "questionType": "Multiple Options",
  "questionLevel": "Easy"
}

### Generating Recipes
POST {{MyGeminiAPI_HostAddress}}/api/Gemini/generate-recipe
Content-Type : application/json
Accept: application/json


{
  "ingredients": [
    "Rice", "potato", "vegetables"
  ], 
  "isVeg": true, 
  "dishRegion": "Indian"
}