@MyGeminiAPI_HostAddress = http://localhost:5122

### Generating Quiz
POST {{MyGeminiAPI_HostAddress}}/api/Gemini/generate-quiz
Content-Type : application/json
Accept: application/json

{
  "questionCount": 3,
  "categoryName": "Random",
  "questionType": "Multiple Options",
  "questionLevel": "Easy"
}

### Generating Recipes
POST {{MyGeminiAPI_HostAddress}}/api/Gemini/generate-recipe
Content-Type : application/json
Accept: application/json


{
  "ingredients": [
    "Rice", "potato", "vegetables"
  ], 
  "isVeg": true, 
  "dishRegion": "Indian"
}

### Generating Code Review
POST {{MyGeminiAPI_HostAddress}}/api/Gemini/review-code
Content-Type : application/json
Accept: application/json


{
  "code": "CODE_SNIPPET ( may provide with some comments )"
}


### Conversation
POST {{MyGeminiAPI_HostAddress}}/api/Gemini/conversation
Content-Type : application/json
Accept: application/json


{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "YOUR_QUERY"
        }
      ]
    }
  ]
}