import { faQuora } from "@fortawesome/free-brands-svg-icons";
import { faAngleRight, faAngleUp, faAt, faBars, faC, faCaretUp, faCircle, faCircleCheck, faCircleQuestion, faCloudArrowUp, faComments, faCreditCard, faDownload, faEllipsis, faHouse, faImage, faListOl, faLock, faLockOpen, faLongArrowLeft, faLongArrowRight, faO, faPaperPlane, faPencil, faPlus, faQ, faSearch, faStopwatch, faTrash, faUserPlus, faUserXmark, faUtensils, faWandMagicSparkles, faXmark } from "@fortawesome/free-solid-svg-icons";

export abstract class FAIcons {
    static readonly LONG_RIGHT_ARROW = faLongArrowRight;
    static readonly LONG_LEFT_ARROW = faLongArrowLeft;
    static readonly RIGHT_ANGLED_ARROW = faAngleRight;
    static readonly UP_ARROW = faCaretUp;
    static readonly ELLIPSES = faEllipsis;
    static readonly USER = faUserPlus;
    static readonly PLUS = faPlus;
    static readonly AT = faAt;
    static readonly LOCK = faLock;
    static readonly LOCK_OPENED = faLockOpen;
    static readonly PAPER_PLANE = faPaperPlane;
    static readonly TRASH = faTrash;
    static readonly BLACK_CIRCLE = faCircle;
    static readonly UP_ANGLE = faAngleUp;
    static readonly Q = faQ;
    static readonly STW = faStopwatch;
    static readonly CLOSE = faXmark;
    static readonly USER_DELETE = faUserXmark;
    static readonly CIRCLE_QS = faCircleQuestion;
    static readonly UPLOAD = faCloudArrowUp;
    static readonly DOWNLOAD = faDownload;
    static readonly PENCIL = faPencil;
    static readonly LIST = faListOl;
    static readonly SEARCH = faSearch;
    static readonly TICK = faCircleCheck;
    static readonly HAMBURGER = faBars;
    static readonly MAGIC_SPARKLES = faWandMagicSparkles;
    static readonly HOME = faHouse;
    static readonly CREDIT_CARD = faCreditCard;
    static readonly QUIZZ = faQuora;
    static readonly C = faC;
    static readonly O = faO;
    static readonly IMAGE = faImage;
    static readonly UTENSIL = faUtensils;
    static readonly CHAT = faComments;
}